language: python
matrix:
  allow_failures:
    - env: TOX_ENV=squeeze
  include:
    - python: 2.6
      env: TOX_ENV=py26
    - python: 2.7
      env: TOX_ENV=py27
    - python: 3.3
      env: TOX_ENV=py33
    - python: 3.4
      env: TOX_ENV=py34
    - python: 3.5
      env: TOX_ENV=py35
    - python: 3.6
      env: TOX_ENV=py36
    - python: 2.6
      env: TOX_ENV=squeeze
    - python: 2.7
      env: TOX_ENV=wheezy
install:
  - pip install -U pip
  - pip install tox
  - sudo rm -rf /dev/shm && sudo ln -s /run/shm /dev/shm
script:
  - tox -e $TOX_ENV
notifications:
  irc:
    channels:
      - "chat.freenode.net#isso"
    on_success: change
    on_failure: always
