name: Python tests

on:
  push:
    paths:
      - "Makefile"
      - "setup.py"
      - "setup.cfg"
      - "contrib/**.py"
      - "isso/**.py"
      - ".github/workflows/python-tests.yml"
  pull_request:
    paths:
      - "Makefile"
      - "setup.py"
      - "setup.cfg"
      - "contrib/**.py"
      - "isso/js/**.py"
      - ".github/workflows/python-tests.yml"

jobs:
  test:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: [3.6, 3.7, 3.8, 3.9, "3.10"]
      fail-fast: false

    steps:

    - name: Check out repository code
      uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }} on ${{ matrix.os }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
        # Dependencies are in setup.py, so use it as cache key
        cache-dependency-path: 'setup.py'

    - name: Install isso dependencies
      # Use pip instead of python setup.py develop to get caching from
      # "setup-python" action
      run: pip install -e .

    - name: Install test suite dependencies
      run: pip install pytest pytest-cov

    - name: Run test suite
      run: make test
      env:
        PYTHONHASHSEED: random

    - name: Install style check dependencies
      run: pip install flake8

    - name: Run style check
      run: make flakes

    - name: Run coverage check, fail if <70%
      run: |
        make coverage
        coverage report --fail-under 70
